# Generated by Django 5.1.3 on 2024-12-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_class_name_alter_subject_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'associated_class')},
        ),
    ]
