# Generated by Django 3.1.12 on 2024-12-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20241217_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.document')),
            ],
        ),
    ]
