# Generated by Django 3.1.12 on 2024-12-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_documentembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_label', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('best_match_sentence', models.TextField()),
                ('similarity_score', models.FloatField()),
                ('answer_relevance', models.CharField(max_length=255)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.document')),
            ],
            options={
                'verbose_name': 'Question-Answer Result',
                'verbose_name_plural': 'Question-Answer Results',
            },
        ),
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('type', models.CharField(choices=[('question', 'Question'), ('answer', 'Answer')], default='question', max_length=14)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='qa.image')),
            ],
        ),
    ]
