# Generated by Django 3.1.12 on 2024-12-17 10:54

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_imageembedding_questionanswerresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='associated_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.class'),
        ),
        migrations.AddField(
            model_name='image',
            name='associated_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.class'),
        ),
        migrations.AlterField(
            model_name='documentembedding',
            name='embedding',
            field=djongo.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='imageembedding',
            name='embedding',
            field=djongo.models.fields.JSONField(),
        ),
    ]
