# Generated by Django 3.1.12 on 2024-12-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_auto_20241217_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='associated_class',
        ),
        migrations.RemoveField(
            model_name='image',
            name='associated_class',
        ),
    ]
