# Generated by Django 3.1.12 on 2024-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_auto_20241217_1148'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['pdf'], name='qa_document_pdf_fb0639_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_at'], name='qa_image_uploade_4eb7f3_idx'),
        ),
    ]
