# Generated by Django 3.1.12 on 2024-12-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20241217_1218'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='qa_document_pdf_fb0639_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='qa_image_uploade_4eb7f3_idx',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['pdf'], name='document_co_pdf_1b0ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_at'], name='image_colle_uploade_c2a17b_idx'),
        ),
        migrations.AlterModelTable(
            name='document',
            table='document_collection',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image_collection',
        ),
    ]
