# Generated by Django 3.1.12 on 2024-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_auto_20241218_0603'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['document'], name='qa_document_documen_76717f_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image'], name='image_colle_image_7e7245_idx'),
        ),
        migrations.AddIndex(
            model_name='imageembedding',
            index=models.Index(fields=['image', 'type'], name='qa_imageemb_image_i_3859e1_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswerresult',
            index=models.Index(fields=['document', 'question_label'], name='qa_question_documen_0a72d6_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswerresult',
            index=models.Index(fields=['similarity_score'], name='qa_question_similar_fe9875_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['associated_class', 'name'], name='qa_subject_associa_b11d64_idx'),
        ),
    ]
