# Generated by Django 3.1.12 on 2024-12-18 07:14

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_auto_20241218_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerresult',
            name='embeddings',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
